services:
  backend:
    build: 
      context: ./src/backend
      args:
        GO_VERSION: $GO_VERSION
        USER_GID: $GID_FILES
        GRP_PERMS: $GID_PERM_FILES
        FS_PATH: $SV_PATH_FILES
    environment:
      - COMPILER_URL=$COMPILER_URL
    ports:
      - $BACKEND_HOST:3000
    volumes:
      - file-store:$SV_PATH_FILES
    
  compiler-ms:
    build: 
      context: ./src/services/compiler
      args:
        GO_VERSION: $GO_VERSION
        USER_GID: $GID_FILES
        GRP_PERMS: $GID_PERM_FILES
        FS_PATH: $SV_PATH_FILES
    ports:
      - $COMPILER_HOST:3001
    volumes:
      - file-store:$SV_PATH_FILES

volumes:
  file-store:
