name: Build Checker
on:
  pull_request:
    branches:
      - 'dev'
      - 'stable'
jobs:
  frontend-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install Node and npm
        uses: actions/setup-node@v6
        with:
          node-version: 22.12.0

      - name: Test Build
        working-directory: ./src/frontend
        run: |
          npm install
          npm run build
  
  backend-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Copy mock environment
        run: cp .env.sample .env

      - name: Run Docker Compose
        run: docker compose up --build

      - name: Clean up
        run: docker compose down
