name: Build Checker
on:
  pull_request:
    branches:
      - 'dev'
      - 'stable'
jobs:
  frontend-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install Node and npm
        uses: actions/setup-node@v6
        with:
          node-version: 22.12.0

      - name: Test Build
        working-directory: ./src/frontend
        run: |
          npm install
          npm run build
  
  backend-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: [./src/backend, ./src/services/compiler]
    steps:
      - uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.22.2'
      
      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.dir }}
          load: true
          tags: go-file:latest
        
      - name: Test Build
        working-directory: ${{ matrix.dir }}
        run: |
          docker run --rm go-file:latest