name: Code Format Checker
on:
  pull_request:
    branches:
      - 'dev'
      - 'stable'
jobs:
  frontend-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install Node and npm
        uses: actions/setup-node@v6
        with:
          node-version: 22.12.0

      - name: Codestyle Check on Frontend
        working-directory: ./src/frontend
        run: |
          npm install
          npm run ng -- lint

  backend-linter:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: [./src/backend, ./src/services/compiler]
    steps:
      - uses: actions/checkout@v6

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.22.2'
          cache: false
      
      - name: Codestyle Check on Backend
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          working-directory: ${{ matrix.dir }}


