name: Code Format Checker
on:
  pull_request:
    branches:
      - 'dev'
      - 'stable'
jobs:
  frontend-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install Node and npm
        uses: actions/setup-node@v6
        with:
          node-version: 22.12.0

      - name: Codestyle Check on Frontend
        working-directory: ./src/frontend
        run: |
          npm install
          npm run ng -- lint
